---
- name: Include tasks
  ansible.builtin.include_tasks:
    file: "{{ file }}.yml"
  loop:
    - desktop
    - suckless
  loop_control:
    loop_var: file

# vim: ft=yaml.ansible ts=2 sts=2 sw=2 et
